export const CLOSING_REGEX = [
  /see you later/i,
  /thank you for your time/i,
  /I'm here if you need anything else/i,
  /it's been a pleasure helping you/i,
  /see you soon/i,
  /have a good day/i,
  /with this we finish/i,
  /you can message me anytime/i,
  /this concludes/i,
  /if you need anything else[,;.!]? let me know/i,
  /it was nice talking with you/i,
  /I wish you much success/i,
  /bye/i,
  /success with your business/i,
  /goodbye/i,
  /see you/i,
  /see you soon/i,
  /have an excellent day/i,
  /see you soon/i,
  /I'll be on standby/i,
  /we'll be on standby/i,
  /anything you need/i,
  /see you soon!/i,
  /I hope to help you in the future/i,
  /I hope you have a great day/i,
  /thanks again for trusting us/i,
  /see you later!/i,
  /see you soon!/i,
  /see you later!/i,
  /until next time!/i,
  /until your next visit!/i,
  /until our next meeting!/i,
];
