export const CLOSING_REGEX = [
    /hasta luego/i,
    /gracias por tu tiempo/i,
    /estoy aquí si necesitas algo más/i,
    /ha sido un placer ayudarte/i,
    /nos vemos pronto/i,
    /que tengas un buen día/i,
    /con esto finalizamos/i,
    /puedes escribirme cuando quieras/i,
    /con esto concluye/i,
    /si necesitas algo más[,;.!]? avísame/i,
    /fue un gusto conversar contigo/i,
    /te deseo mucho éxito/i,
    /chao/i,
    /éxito con tu emprendimiento/i,
    /ad[ií]os/i,
    /nos vemos/i,
    /nos vemos pronto/i,
    /tengas un excelente día/i,
    /hasta pronto/i,
    /quedo atento/i,
    /quedamos atentos/i,
    /cualquier cosa/i,
    /¡hasta pronto!/i,
    /espero poder ayudarte en el futuro/i,
    /espero que tengas un excelente d[ií]a/i,
    /Gracias nuevamente por confiar en nosotros/i,
    /¡Hasta luego!/i,
    /¡Hasta pronto!/i,
    /¡Hasta la vista!/i,
    /¡Hasta la próxima!/i,
    /¡Hasta la próxima visita!/i,
    /¡Hasta la próxima reunión!/i,
    

  ];