const countryList = [
  "Albania",
  "Alemania",
  "Andorra",
  "Antigua y Barbuda",
  "Argentina",
  "Australia",
  "Austria",
  "Bahamas",
  "Barbados",
  "Bélgica",
  "Belice",
  "Bielorrusia",
  "Bolivia",
  "Bosnia y Herzegovina",
  "Brasil",
  "Bulgaria",
  "Canadá",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Croacia",
  "Cuba",
  "Dinamarca",
  "Dominica",
  "Ecuador",
  "El Salvador",
  "Eslovaquia",
  "Eslovenia",
  "España",
  "Estados Unidos",
  "Estonia",
  "Finlandia",
  "Francia",
  "Granada",
  "Grecia",
  "Guatemala",
  "Guyana",
  "Haití",
  "Honduras",
  "Hungría",
  "India",
  "Irlanda",
  "Islandia",
  "Italia",
  "Jamaica",
  "Japón",
  "Letonia",
  "Liechtenstein",
  "Lituania",
  "Luxemburgo",
  "Macedonia del Norte",
  "Malta",
  "México",
  "Moldavia",
  "Mónaco",
  "Montenegro",
  "Nicaragua",
  "Noruega",
  "Países Bajos",
  "Panamá",
  "Paraguay",
  "Perú",
  "Polonia",
  "Portugal",
  "Reino Unido",
  "República Checa",
  "República Dominicana",
  "Rumanía",
  "Rusia",
  "San Cristóbal y Nieves",
  "San Marino",
  "San Vicente y las Granadinas",
  "Santa Lucía",
  "Serbia",
  "Suecia",
  "Suiza",
  "Surinam",
  "Taiwán",
  "Trinidad y Tobago",
  "Turquía",
  "Ucrania",
  "Uruguay",
  "Vaticano",
  "Venezuela",
  "other",
];

const industry = [
  "Agua",
  "Alimentos",
  "Básica",
  "Distribuidor",
  "Generación",
  "Industrial",
  "Mineria",
  "O&G",
  "OEM",
  "Otros",
  "Servicios",
  "Trading",
  "Agencia",
  "Catering",
  "Transporte",
  "Productora",
  "Marketing",
  "Educación",
  "Gobierno",
  "Farmacia",
  "Tecnología",
  "Belleza",
  "Fitness",
  "Infantil",
  "Deportes",
  "Finanzas y Cripto",
  "Salud y Bienestar",
  "Juegos",
  "other",
];

[
  `"Agua", "Alimentos", "Básica", "Distribuidor", "Generación", "Industrial", "Mineria", "O&G", "OEM", "Otros", "Servicios", "Trading", "Agencia", "Catering", "Transporte", "Productora", "Marketing", "Educación", "Gobierno", "Farmacia", "Tecnología", "Belleza", "Fitness", "Infantil", "Deportes", "Finanzas y Cripto", "Salud y Bienestar", "Juegos", "other"`,
];
